" main vimrc file

" VIMDIR should be defined!

" load settings which are not public
let private_file=expand("$HOME/" . VIMDIR . "/rc/vimrc.private")

if filereadable(private_file)
    exec "source " . private_file
endif

" load vim options
exec ":source $HOME/" . VIMDIR . "/rc/vim.options.rc"

" load plugin options
exec "source $HOME/" . VIMDIR . "/rc/plugin.options.rc"

" load keyboard mappings
exec "source $HOME/" . VIMDIR . "/rc/mappings.rc"

" load my own functions and commands
exec "source $HOME/" . VIMDIR . "/rc/custom.rc"

" load all plugins from ~/VIMDIR/bundle/
call pathogen#infect()

" load all help text from ~/VIMDIR/bundle/
Helptags
