" main vimrc file

if has("win32") || has ("win16") || exists("g:cygwin")
    let VIMDIR="Documents/GitHub/vim"
else
    let VIMDIR=".vim"
endif

" load vim options
exec ":source $HOME/" . VIMDIR . "/rc/vim.options.rc"

" load plugin options
exec "source $HOME/" . VIMDIR . "/rc/plugin.options.rc"

" load keyboard mappings
exec "source $HOME/" . VIMDIR . "/rc/mappings.rc"

" load my own functions and commands
exec "source $HOME/" . VIMDIR . "/rc/custom.rc"

" load all plugins from ~/VIMDIR/bundle/
call pathogen#infect()

" load all help text from ~/VIMDIR/bundle/
Helptags
